#!/bin/bash

exec 2>&1

touch "$HOME/.aria2.session"

DL_DIR="$HOME/.aria2downloads"

mkdir -p "$DL_DIR"

HOOKS="$HOME/.config/aria2/hooks"

#exec aria2c --dir="$HOME/downloads" \
exec cgexec -g net_cls:vpn1 aria2c --dir="$DL_DIR" \
    --on-download-complete="$HOOKS"/aria2hook-complete \
    --on-download-pause="$HOOKS"/aria2hook-pause \
    --on-download-start="$HOOKS"/aria2hook-start \
    --on-download-error="$HOOKS"/aria2hook-error \
    --on-download-stop="$HOOKS"/aria2hook-stop \
    --enable-dht=true \
    --enable-dht6=false \
    --disable-ipv6=true \
    --check-certificate=false \
    --check-integrity=true \
    --continue=true \
    --max-tries=0 \
    --retry-wait=3 \
    --timeout=60 \
    --max-connection-per-server=4 \
    --log-level=error \
    --http-accept-gzip=true \
    --max-concurrent-downloads=5 \
    --pause-metadata=false \
    --input-file="${HOME}/.aria2.session" \
    --save-session="${HOME}/.aria2.session" \
    --save-session-interval=10 \
    --force-save=true \
    --always-resume=true \
    --allow-overwrite=true \
    --rpc-listen-all=false \
    --enable-rpc=true
