#!/usr/bin/env bash

KEY='E:Print'

runner() {
  local name dir="$HOME/.screenshots"

  mkdir -p "$dir"

  local numMonitors

  read -r _ numMonitors < <(xrandr --listactivemonitors)

  for m in $(seq 1 "$numMonitors"); do
    (( m-- ))
    name="$dir/screenshot-M${m}-$(date "+%F_%T")"-'$wx$h.png'
    scrot -zio -M "$m" -F "$name" && notify "Screen shot!"
  done

}
