#!/usr/bin/env bash

KEY='E:Insert'

runner() {
  local name dir="$HOME/.screenshots"
  mkdir -p "$dir"
  name="$dir/windowshot-$(date "+%F_%T")"-'$wx$h.png'

  scrot -ziow "$(xdotool getwindowfocus)" -F "$name" && notify "Window shot!"
}
