#!/usr/bin/env bash

PERIOD=30

KEYS[prev]='C-M:d'
prev() {
	xbacklight -dec 5
}

KEYS[next]='C-M:u'
next() {
	xbacklight -inc 5
}

KEYS[toggle]='C-M:f'
toggle() {
	read -r backlight < <(xbacklight | xargs printf "%02.f")
	if ((backlight <= 30)); then
		xbacklight -set 100
	else
		xbacklight -set 30
	fi
}

ctl() {
	local cmd

	if xbacklight &>/dev/null; then
		cmd=xbacklight
	elif xrandr &>/dev/null; then
		local monitors
		readarray -t monitors < <(xrandr --listactivemonitors | sed -nr '2,$p' |
			awk '{print $4}')
		for mon in "${monitors[@]}"; do
			xrandr --output "$mon" --brightness
		done
	fi
}

text() {
  local backlight

	read -r backlight < <(xbacklight | xargs printf "%02.f")

  [[ $? -ne 0 ]] && backlight='**'

	printf "%s" "$(fmt "$backlight")"
}

icon() {
	local icon=
	local icon=󰃞
	local icon=󰃠
  local icon=󰌶

	local color=blueviolet

	printf "%s" "$(colorize "$color" "$icon")"
}
