#!/usr/bin/env bash

PERIOD=10

REGEX='/Default/s/.*ID: (.*), Name.*/\1/p'

read -r ID < <(pulsemixer --list-sources | sed -rn "$REGEX")

KEYS[prev]='C-M:h'
prev() {
	pulsemixer --id "$ID" --change-volume -5 --max-volume 100
	#wpctl set-volume @DEFAULT_SOURCE@ 5%-
}

KEYS[next]='C-M:l'
next() {
	pulsemixer --id "$ID" --change-volume +5 --max-volume 100
	#wpctl set-volume @DEFAULT_SOURCE@ 5%+
}

KEYS[toggle]='C-M:i'
toggle() {
	pulsemixer --id "$ID" --toggle-mute
	#wpctl set-volume @DEFAULT_SOURCE@ toggle
}

run() {
	menu pulse
}

text() {
	local volume
	read -r volume < <(pulsemixer --id "$ID" --get-volume | awk '{print $1}')
	#read -r _ volume _ < <(wpctl get-volume @DEFAULT_SOURCE@)
	echo -n "$(fmt "${volume#*.}")"
}

icon() {
	local ok=󰍬
	local ko=󰍭

	read -r mute < <(wpctl get-volume @DEFAULT_SOURCE@)
	case "$mute" in
	*MUTE*) echo -n "$ko" ;;
	*) echo -n "$ok" ;;
	esac
}
