#!/usr/bin/env bash

PERIOD=10

KEYS[prev]='C-M:h'
prev() {
	gui pulse ctl source dec
}

KEYS[next]='C-M:l'
next() {
	gui pulse ctl source inc
}

KEYS[toggle]='C-M:i'
toggle() {
	gui pulse ctl source mute
}

run() {
	tmux set -s "@menu-pulse-mode" sources
	menu auto pulse
}

text() {
	local vol

	read -r vol < <(gui pulse ctl source getvol)

	vol="${vol%\%}"

	printf "%s" "$(fmt "${vol#*.}")"
}

icon() {
	local ok=󰍬
	local ko=󰍭

	local icon
	local color=gold

	read -r mute < <(gui pulse ctl source getmute)

	case "$mute" in
	true)
		icon="$ko"
		;;
	false)
		icon="$ok"
		;;
	esac

	printf "%s" "$(colorize "$color" "$icon")"
}
