#!/usr/bin/env bash

PERIOD=10

text() {
  local type ifname signal name

  IFS=: read -r _ _ type signal name < <(gui connection name)

  [[ "$type" == wifi ]] && name="$name (${signal}%)"

  printf "%s" "$name"
}

icon() {
    local icon
    local unknown=󱕆
    local wireless=󰖩
    local ethernet=󰀂
    local ethernet=󰈁
    local ethernet=󰈀

    local type

    IFS=: read -r _ type _ < <(gui connection name)

    case "$type" in
        wifi) icon="$wireless";;
        ethernet) icon="$ethernet";;
        *) icon="$unknown";;
    esac

    printf "%s" "$icon"
}
