#!/usr/bin/env bash

PERIOD=60

run() {
  menu auto date
}

text() {
	local time=$(date '+%R')
	local time=$(date '+%I:%M %p')
	local time=$(date '+%a %b %d')

	printf "%s" "$time"
}

icon() {
	local icon=
	printf "%s" "$icon"
}

output() {
	printf ":"
	text
}
