#!/usr/bin/env bash

PERIOD=10

run() {
	menu auto aria
}

KEYS[toggle]='C-M:a'
toggle() {
  gui aria toggleAll
}

text() {
	local count
  read -r count < <(gui aria request count)
	printf "%s" "$(fmt "$count")"
}

icon() {
	local icon=󰄠
	local color=aqua

	colorize "$color" "$icon"
}
