#!/usr/bin/env bash

PERIOD=10

run() {
	menu auto aria
}

KEYS[toggle]='C-M:a'
toggle() {
	# aria2p toggle-all
	:
}

text() {
	local count
	read -r count < <(aria2p show 2>/dev/null |
		sed -rn '2,$ { /active/p }' | wc -l)
	printf "%s" "$(fmt "$count")"
}

icon() {
	local icon=󰄠
	local color=aqua

	colorize "$color" "$icon"
}
