#!/usr/bin/env bash

PERIOD=10

toggle() {
  mailsync
}

text() {
    local count

    read -r count < <(notmuch count tag:unread)
    printf "%s" "$count"
}

icon() {
  local icon=
  local icon=󰴃
  printf "%s" "$icon"
}

