#!/usr/bin/env bash

PERIOD=30

toggle() {
	mailsync
}

run() {
	menu auto mail
}

text() {
	local count

	read -r count < <(notmuch count tag:unread)
	printf "%s" "$(fmt "$count")"
}

icon() {
	local icon=
	local icon=󰴃
	local color=lime

	printf "%s" "$(colorize "$color" "$icon")"
}
