#!/usr/bin/env bash

PERIOD=10

unread() {
	local db="$HOME/.local/share/newsboat/cache.db"
	local day=$((3600 * 24))
	local age=1
	local epoch=$(($(date +%s) - ($age * $day)))

	sqlite3 "$db" \
		"SELECT count(*) FROM rss_item WHERE unread == 1 and pubDate > $epoch"
}

text() {
	local count
	local color=skyblue

	read -r count < <(unread)

	# colorize "$color" "$(fmt "$count")"
	fmt "$count"
}

icon() {
	local icon=󰑫
	local color=red

	colorize "$color" "$icon"
}
