#!/usr/bin/env bash

PERIOD=30

KEYS[prev]='C-M:j'
prev() {
	gui pulse ctl sink dec
}

KEYS[next]='C-M:k'
next() {
	gui pulse ctl sink inc
}

KEYS[toggle]='C-M:o'
toggle() {
	gui pulse ctl sink mute
}

run() {
	tmux set -s "@menu-pulse-mode" sinks
	menu auto pulse
}

text() {
	local vol

	read -r vol < <(gui pulse ctl sink getvol)

	vol="${vol%\%}"

	printf "%s" "$(fmt "${vol#*.}")"
}

icon() {
	local ok=󰕾
	local ko=󰖁

	local icon
	local color=mediumspringgreen

	read -r mute < <(gui pulse ctl sink getmute)

	case "$mute" in
	true) icon="$ko" ;;
	false) icon="$ok" ;;
	esac

	colorize "$color" "$icon"
}
