#!/usr/bin/env bash

PERIOD=5

run() {
	menu process
}

text() {
	local text availram totalram

	# read -r availram < <(free | awk '/^Mem:/ {print $7}')
	read -r usedram < <(free | awk '/^Mem:/ {print $3}')
	read -r totalram < <(free | awk '/^Mem:/ {print $2}')
	read -r text < <(bc <<< "$usedram * 100 / $totalram")
	printf "%s" "$(fmt "$text")"
}

icon() {
  local icon_not_updating=󰈰
  local icon_updating=
  local icon="$icon_not_updating"

	local color=gold

  local sfile=/tmp/UPDATING

  [[ -r "$sfile" ]] && icon="$icon_updating"

	printf "%s" "$(colorize "$color" "$icon")"
}
