#!/usr/bin/env bash

PERIOD=300

run() {
  menu auto time
}

text() {
  local temp city

  read -r city < <(basename "$(readlink /etc/localtime)")
  read -r temp < <(bkt --ttl 5m --stale 10s -- gui time weather "$city" |
    awk '/^feeltemp/ {print $2}')

  [[ -z "$temp" ]] && temp='**'

  echo -n "$temp"
}

icon() {
  local icon=

  echo -n "$icon"
}
