#!/usr/bin/env bash

KEY='E:Print'

function runner() {
  local name dir="$HOME/.screenshots"

  mkdir -p "$dir"
  name="$dir/screenshot-$(date "+%F_%T")"-'$wx$h.png'

  scrot -zio -F "$name" && notify "Screen shot!"
}
