#!/usr/bin/env bash

KEY='E:Delete'

runner() {
  local name dir="$HOME/.screenshots"
  mkdir -p "$dir"
  name="$dir/selectshot-$(date "+%F_%T")"-'$wx$h.png'

  scrot -zios -F "$name" && notify "Selection shot!"
}
