#!/usr/bin/env bash

ATTRIBUTES=(profile=spotify)

function runner() {
  local username="$(gui pass grab spotify.com username)"
  local password="$(gui pass grab spotify.com password)"

  exec vpn 2 spotify --username="$username" --password="$password"
}
