#!/usr/bin/env bash

KEY='S-W:e'

ATTRIBUTES=(profile=vpnqute)
COMMAND=(cgexec -g net_cls:vpn1
  qutebrowser --qt-arg name vpnqute --target private-window --temp-basedir
  --config-py "$HOME/.config/qutebrowser/config.py")
