#!/usr/bin/env bash

KEY=d
MOD='S-M'
ICON=

HORIZONTAL=1

export ICON_DL=
export ICON_UL=

query() {
  local query params method="$1"
  local URL=http://localhost:6800/jsonrpc

  shift

  if [[ -n "$*" ]]; then
    read -r params < <(IFS=,; printf "%s" "$*")
    params="\"params\": [ $params ]"
  fi

  read -r -d '' query << EOF
  {
    "jsonrpc": "2.0",
    "id": "menu",
    "method": "$method",
    $params
  }
EOF

  curl -sL -X POST -H 'Content-Type: application/json' -d "$query" "$URL" |
    jq -r '.result'
}

request() {
  local method="$1"
  local gid="$2"

  shift 2

  case "$method" in
    stats)
      query aria2.getGlobalStat
      ;;
    status)
      query aria2.tellStatus "$gid"
      ;;
    list)
      local numWaiting numStoppedTotal

      IFS=$'\n' read -r -d '' numWaiting numStoppedTotal < <(
        query aria2.getGlobalStat | jq -r '(.numWaiting, .numStoppedTotal)'
      )

      jq -n 'reduce inputs as $in
        (null; . + if $in|type == "array" then $in else [$in] end)' < <(
        query aria2.tellActive
        query aria2.tellWaiting 0 "$numWaiting"
        query aria2.tellStopped 0 "$numStoppedTotal"
      )
      ;;
    count)
      local numActive numWaiting numStoppedTotal

      IFS=$'\n' read -r -d '' numActive numWaiting numStoppedTotal < <(
        query aria2.getGlobalStat |
          jq -r '(.numActive, .numWaiting, .numStoppedTotal)'
      )

      printf "%d\n" $((numActive + numWaiting + numStoppedTotal))
      ;;
    files)
      query aria2.getFiles "\"$gid\""
      ;;
    pause)
      query aria2.pause "\"$gid\""
      ;;
    pauseAll)
      query aria2.pauseAll
      ;;
    unpause)
      query aria2.unpause "\"$gid\""
      ;;
    unpauseAll)
      query aria2.unpauseAll
      ;;
    add)
      local uri="$gid"
      query aria2.addUri "\"$gid\""
      ;;
    del)
      query aria2.remove "\"$gid\""
      ;;
    rm)
      query aria2.forceRemove "\"$gid\""
      ;;
    getgopt)
      query aria2.getGlobalOption
      ;;
    setgopt)
      local opts=("$@")
      query aria2.changeGlobalOption "${opts[@]}"
      ;;
    getopt)
      query aria2.getOption "\"$gid\""
      ;;
    setopt)
      local opts=("$@")
      query aria2.changeOption "\"$gid\"" "${opts[@]}"
      ;;
  esac
}

label() {

  local ul dl maxuspeed maxdspeed

  IFS=$'\n' read -r -d '' dl ul < <(
    request stats | jq -r '(.downloadSpeed, .uploadSpeed)'
  )

  read -r maxdspeed < <(request getgopt | jq -r '."max-download-limit"')
  read -r maxuspeed < <(request getgopt | jq -r '."max-upload-limit"')

  maxdspeed="$(numfmt --to=iec --suffix=Bps "$maxdspeed")"
  maxuspeed="$(numfmt --to=iec --suffix=Bps "$maxuspeed")"
 
  dl="$(numfmt --to=iec --suffix=Bps "$dl")"
  ul="$(numfmt --to=iec --suffix=Bps "$ul")"

  printf " $ICON_DL %s $ICON_UL %s " "$dl/$maxdspeed" "$ul/$maxuspeed"
}

view() {
  local gid
  read -r gid _ <<< "$1"

  request files "$gid" | yq -yC | bat -p --force-colorization --language=yaml
}

OPTS+=(--with-nth 2..)
list() {
  local list

  IFS= read -r -d '' list < <(request list)

  local gid status dled uled total conns dspeed uspeed names
  local progress maxuspeed maxdspeed dlh ulh th dsh ush

  readarray -t gid < <(jq -r '.[] | .gid' <<< "$list")
  readarray -t status < <(jq -r '.[] | .status' <<< "$list")
  readarray -t dled < <(jq -r '.[] | .completedLength' <<< "$list")
  readarray -t uled < <(jq -r '.[] | .uploadLength' <<< "$list")
  readarray -t total < <(jq -r '.[] | .totalLength' <<< "$list")
  readarray -t conns < <(jq -r '.[] | .connections' <<< "$list")
  readarray -t dspeed < <(jq -r '.[] | .downloadSpeed' <<< "$list")
  readarray -t uspeed < <(jq -r '.[] | .uploadSpeed' <<< "$list")
  readarray -t names < <(jq -r '.[] | .files.[0].uris.[0].uri' <<< "$list" |
    xargs basename -a)

  for i in "${!gid[@]}"; do
    unset dsh ush dlh ulh th maxuspeed maxdspeed

    dsh="$(numfmt --to=iec --suffix=Bps "${dspeed[$i]}")"
    ush="$(numfmt --to=iec --suffix=Bps "${uspeed[$i]}")"

    dlh="$(numfmt --to=iec --suffix=B "${dled[$i]}")"
    ulh="$(numfmt --to=iec --suffix=B "${uled[$i]}")"

    th="$(numfmt --to=iec --suffix=B "${total[$i]}")"

    read -r maxdspeed < <(request getopt "${gid[$i]}" |
      jq -r '."max-download-limit"')
    read -r maxuspeed < <(request getopt "${gid[$i]}" |
      jq -r '."max-upload-limit"')

    maxdspeed="$(numfmt --to=iec --suffix=Bps "$maxdspeed")"
    maxuspeed="$(numfmt --to=iec --suffix=Bps "$maxuspeed")"

    progress[$i]="$(printf "%0.0f" \
      "$(echo "${dled[$i]} * 100. / ${total[$i]}" | bc)")"

    printline \
      "${gid[$i]}" "$iSEP" \
      "${status[$i]}" "$iSEP" \
      "$(colorize blueviolet "${progress[$i]}%")" "$iSEP" \
      "$(colorize royalblue "$ICON_DL $dlh/$th")" "$iSEP" \
      "$(colorize royalblue "$dsh/$maxdspeed")" "$iSEP" \
      "$(colorize yellow "$ICON_UL $ulh")" "$iSEP" \
      "$(colorize yellow "$ush/$maxuspeed")" "$iSEP" \
      "$(colorize red "$(basename "${names[$i]}")")"
  done | column -t -s "$iSEP"
}

BINDS[del]=alt-d
DESCS[del]='Delete entry'
del() {
  local gid files
  read -r gid _ <<< "$1"

  readarray -t files < <(request files "$gid" |
    jq -r '.[].path')

  request del "$gid"

  for f in "${files[@]}"; do
    [[ -e "${f}.aria2" ]] && rm "${f}.aria2"
  done
}

BINDS[dinc]=alt-l
DESCS[dinc]='Increase Download Speed'
dinc() {
  local gid dlimit

  read -r gid _ <<< "$1"

  read -r dlimit < <(request getopt "$gid" | jq -r '."max-download-limit"')

  if (( dlimit < 1024 * 1024 )); then
    dlimit=$((dlimit + 1024 * 10))
  else
    dlimit=$((dlimit + 1024 * 1024))
  fi

  request setopt "$gid" \
    "$(printf '{ "max-download-limit":"%d" }' "$dlimit")"
}

BINDS[ddec]=alt-h
DESCS[ddec]='Decrease Download Speed'
ddec() {
  local gid dlimit

  read -r gid _ <<< "$1"

  read -r dlimit < <(request getopt "$gid" | jq -r '."max-download-limit"')

  if (( dlimit < 1024 * 1024 )); then
    dlimit=$((dlimit - 1024 * 10))
  else
    dlimit=$((dlimit - 1024 * 1024))
  fi

  request setopt "$gid" \
    "$(printf '{ "max-download-limit":"%d" }' "$dlimit")"
}

BINDS[toggle]=enter
DESCS[toggle]='Toggle pause'
toggle() {
  local gid status
  read -r gid status _ <<< "$1"

  case "$status" in
    paused)
      request unpause "$gid"
      ;;
    active)
      request pause "$gid"
      ;;
  esac
}

BINDS[refresh]=alt-r
DESCS[refresh]='Refresh status'
refresh() {
  :
}

restart() {
  :
}
