#!/usr/bin/env bash

KEY=d
MOD='S-M'
ICON=

HORIZONTAL=1

ctl() {
  # remove forceRemove
  # add
  # pause forcePause
  # pause-all forcePauseAll
  #
  local -A methods=(
    [add]=addUri
    [del]=remove
    [Del]=forceRemove
    [dela]=
    )

  case "$kind" in
    add)
      ;;
    del)
      ;;
    toggle)
      ;;
    toggleAll)
      ;;
    stats)
      ;;

  esac
}

query() {
  local query params method="$1"
  local URL=http://localhost:6800/jsonrpc

  if [[ $# -ge 2 ]]; then
    read -r params < <(IFS=,; printf '"params": [%s]' "${*:2}")
  fi

  read -r -d '' query << EOF
  {
    "jsonrpc": "2.0",
    "id": "menu",
    "method": "$method",
    ${params}
  }
EOF

  curl -sL -X POST -H 'Content-Type: application/json' -d "$query" "$URL" |
    jq -r '.result'
}

request() {
  local method="$1"
  shift
  local params=("$@")

  case "$method" in
    stats)
      query aria2.getGlobalStat
      ;;
    status)
      ;;
    list)
      local numWaiting numStoppedTotal

      IFS=$'\n' read -r -d '' numWaiting numStoppedTotal < <(
        query aria2.getGlobalStat | jq -r '(.numWaiting, .numStoppedTotal)'
      )

      jq -n 'reduce inputs as $in
        (null; . + if $in|type == "array" then $in else [$in] end)' < <(
        query aria2.tellActive
        query aria2.tellWaiting 0 "$numWaiting"
        query aria2.tellStopped 0 "$numStoppedTotal"
      )
      ;;
    toggle)
      query aria2.pause "$@"
      ;;
    toggleAll)
      ;;
    add)
      query aria2.addUri "${params[@]}"
      ;;
    del)
      ;;
    getgopt)
      query aria2.getGlobalOption
      ;;
    setgopt)
      ;;
    getopt)
      ;;
    setopt)
      ;;
  esac
}


view() {
  :
}

label() {
  declare -A -x -g STATS

  local -a values
  local -a keys=(
    downloadSpeed
    uploadSpeed
    numActive
    numStopped
    numStoppedTotal
    numWaiting
  )

  readarray -t values < \
    <(request stats | jq -r "$(IFS=,; printf '%s' "${keys[*]/#/.}")")

  for i in $(seq 0 $((${#values[@]} -1))); do
    if [[ "${keys[$i]}" == *Speed ]]; then
      values[$i]="$(numfmt --to=iec --suffix=B <<< "${values[$i]}")"
    fi
    STATS[${keys[$i]}]="${values[$i]}"
  done

  printf "  %s/s  %s/s 󰧩 %s 󰒲 %s 󰙧 %s 󱕱 %s " "${values[@]}"
  export "$(declare -p STATS)"
}

list() {
  # [GID] TYPE? STATUS completedLength/totalLength uploadedLength dSpeed/dMaxSpeed uSpeed/uMaxSpeed
  # #numpieces 
  local flatkey
  local -a values
  local -a keys=(
    gid
    status
    completedLength
    totalLength
    #connections
    #dir
    #downloadSpeed
    #uploadSpeed
    #uploadLength
    #numPieces
  )
  silent label
  read -r flatkey < <(IFS=,; printf '%s' "${keys[*]/#/.}")
  # .bittorrent.info.name

  f() {
    query "$@" | jq -r ".[]|${flatkey}"
  }

  readarray -t values < <(f stopped 0 "${STATS[numStopped]}")
  readarray -t values < <(f paused)
  readarray -t values < <(f active)
  printf "%s %s %s %s\n" "${values[@]}"
}

BINDS[remove]=alt-r
DESCS[remove]='Remove download entry'
remove() {
  local id
  read -r id _ <<< "$1"
  aria2p rm "$id"
  aria2p purge
}
