#!/usr/bin/env bash

KEY=t
MOD='S-M'
ICON=

HORIZONTAL=1

NOWRAP=1

function view() {
  local winid
  read -r winid < <(awk '{print $1}' <<< "$1")
  awm info window="$winid"
}

function list() {
  awm list
}

BINDS[open]=enter
DESCS[open]='Raise window entry'
function open() {
  local winid
  read -r winid < <(awk '{print $1}' <<< "$1")
  awm raise window="${winid/:/=}"
}

BINDS[close]=alt-d
DESCS[close]='Close window entry'
function close() {
  local winid
  read -r winid < <(awk '{print $1}' <<< "$1")
  awm kill window="${winid/:/=}"
}
