#!/usr/bin/env bash

KEY=c
MOD='S-M'
ICON=

function view() {
  curl -sL cht.sh/$1
}

function list() {
  curl -sL cht.sh/:list
}

BINDS[open]=enter
DESCS[open]='Choose line (needs rework)'
function open() {
  local f="$(mktemp --dry-run)"

  view "$1" | fzf --ansi -f '' > "$f"
  command open "$f"
}
