#!/usr/bin/env bash

KEY=c
MOD='S-M'
ICON=
COLOR=indianred

view() {
	curl -sL cht.sh/$1
}

list() {
	curl -sL cht.sh/:list
}

BINDS[open]=enter
DESCS[open]='Choose line (needs rework)'
open() {
	local f="$(mktemp --dry-run)"

	view "$1" | fzf --ansi -f '' >"$f"
	command open "$f"
}
