#!/usr/bin/env bash

KEY=y
MOD='S-M'
ICON=

HORIZONTAL=1

function view() {
  local bufnum
  read -r bufnum _ <<< "$1"
  tmux show-buffer -b "$bufnum"
}

function list() {
  tmux list-buffers -F '#{buffer_name} #{buffer_sample}'
}

BINDS[del]=alt-d
DESCS[del]='Delete buffer'
function del() {
  local buf
  read -r buf _ <<< "$1"
  tmux delete-buffer -b "$buf"
}

BINDS[delall]=alt-a
DESCS[dellall]='Delete buffer'
function delall() {
  local buffers
  readarray -t buffers < <(tmux list-buffers -F '#{buffer_name}')

  for buf in "${buffers[@]}"; do
    tmux delete-buffer -b "$buf"
  done
}

function clip() {
  tmux load-buffer - <<< "${1:1}"
  notify "Clipped '${1:1}'"
}

function fork() {
  local origin="$1"
  local pathname="$2"

  IFS=/ read -r _ user repo _ <<< "$pathname"

  cd "$HOME/workspace/repos" && {
    [[ -d "$repo" ]] && notify "Repo '$repo' already exists" || {
      git clone "$origin/$user/$repo" "$repo" && notify "Cloned '$repo'" ||
        notify "Failed to clone '$repo'"
      }
  }
}
