#!/usr/bin/env bash

KEY=f
MOD='S-M'
ICON=󰴽

HORIZONTAL=1
PREVIEW_LABEL_OFFSET=2

function view() {
  local y
}

function label() {
  local mode="$(get_opt mode)"

  echo " mode: $mode "
}

function previewlabel() {
  local mode="$(get_opt mode)"

  echo " $(dolist "$mode-header") "
}

function init() {
  set_opt mode connections
}

function dolist() {
  local kind="$1"

  case "$kind" in
    ssids)
      nmcli -c yes -f active,BSSID,SSID,CHAN,RATE,SIGNAL,FREQ,SECURITY \
        device wifi list --rescan yes | tail +2
      ;;
    ssids-header)
      nmcli -c yes -f BSSID,SSID,CHAN,RATE,SIGNAL,FREQ,SECURITY \
        device wifi list --rescan yes | head -1
      ;;
    connections)
      nmcli -c yes -f NAME,UUID,TYPE,AUTOCONNECT,AUTOCONNECT-PRIORITY \
        connection show | tail +2
      ;;
    connections-header)
      nmcli -c yes -f NAME,UUID,TYPE,AUTOCONNECT,AUTOCONNECT-PRIORITY \
        connection show | head -1
      ;;
  esac
}

function list() {
  local mode="${1:-$(get_opt mode)}"

  set_opt mode "$mode"

  dolist "$mode"
}

BINDS[rotate_mode]=alt-t
HOOKS[rotate_mode]=clear
DESCS[rotate_mode]='Rotate mode'
function rotate_mode() {
  local mode="$(get_opt mode)"

  case "$mode" in
    connections) set_opt mode ssids ;;
    ssids) set_opt mode connections ;;
  esac
}
