#!/usr/bin/env bash

KEY=a
MOD='S-M'
ICON=󰀆

POSITION=BOTTOM

function view() {
  local id

  read -r id _ <<< "$1"

  khard show -u "$id" --format yaml 2>/dev/null | yq
}

function list() {
  local uids
  readarray -t uids < <(khard list -p -F uid)
  printf "%s\n" "${uids[@]}"
}
