#!/usr/bin/env bash

KEY=x
MOD='S-M'
ICON=󱑎
COLOR=bisque

NOWRAP=1
RATIO=50%
FOLLOW=1
HORIZONTAL=1

label() {
  :
}

view() {
  local year="$(date +%Y)"

  read -r uid cal org loc status day date month year _ <<< "$1"

  local d1="$(date -d "$date $month $year" "+%F")"
  local d2="$(date -d "$date $month $((year+1))" "+%F")"

  khal --color calendar "$d1" "$d2"
}

OPTS+=(--with-nth 2.. --header-lines=1)
list() {
  local keys=(
    uid
    calendar
    organizer
    location
    status
    start-date-long
    start-time
    duration
    title
  )

  for k in "${!keys[@]}"; do
    keys[$k]="{${keys[$k]}}"
  done

  read -r -d '' keys < <(IFS="$iSEP"; printf "%s" "${keys[*]}")

  while IFS="$iSEP" read -r uid cal org loc status date time duration title
  do
    printfmt \
      "$uid" \
      "${cal:---}" \
      "${org:---}" \
      "${loc:---}" \
      "${status:---}" \
      "${date:---}" \
      "${time:---}" \
      "${duration:---}" \
      "${title:---}"
  done < <(khal --color list --day-format '' --format "$keys" today 365d) |
    column -t -s "$iSEP" -N UID,CAL,ORG,LOC,STATUS,DATE,TIME,DURATION,TITLE
}

# add event
#   cal:cal_name org:org_name loc:location status:status
# edit event
# del event
# tick/untick event
# rotate STATUS

BINDS[open]=enter
DESCS[open]='Open date in khal'
open() {
  :
}
