#!/usr/bin/env bash

KEY=m
MOD='S-M'
ICON=

HORIZONTAL=1

label() {
	local thread
	read -r thread _ <<<"$1"
	echo "$thread"
}

view() {
	local thread

	read -r thread _ <<<"$1"

	readarray -t files < <(notmuch search --output=files "$thread")

	local i=0
	for file in "${files[@]}"; do
		[[ $i -ne 0 ]] && sepline
		echo "$file"
		sepline
		mu view "$file" | bat -p --force-colorization --language=Email
		((i++))
	done
}

mails() {
	notmuch search --sort=newest-first --output=summary --format=json tag:inbox
}

# del
# tag read
# tag unread
# open in neomutt
# Vkk

OPTS+=(--with-nth 2..)
list() {
	# @menu-mail-list inbox|sent|draft|archive
	local authors subjects mails
	local author_color=red
	local subject_color=yellow

	IFS= read -r -d '' mails < <(mails)

	readarray -t threads < <(jq -r ".[].thread" <<<"$mails")
	readarray -t authors < <(jq -r ".[].authors" <<<"$mails")
	readarray -t subjects < <(jq -r ".[].subject" <<<"$mails")

	for i in "${!authors[@]}"; do
		printf "%s%s%s%s%s\n" "${threads[$i]}" "$iSEP" \
			"$(colorize "$author_color" "${authors[$i]:0:30}")" "$iSEP" \
			"$(colorize "$subject_color" "${subjects[$i]}")"
	done | column -t -s "$iSEP"
}

BINDS[tag]=alt-q
HOOKS[tag]=tag
CALLS[tag]='execute-silent(%s {1} {q})+reload-sync(list)'
tag() {
	local term="$1"
	notmuch tag -unread "$term"
}
