#!/usr/bin/env bash

KEY=m
MOD='S-M'
ICON=

HORIZONTAL=1

label() {
  local thread
  read -r thread _ <<< "$1"
  echo "$thread"
}

view() {
  local thread
  read -r thread _ <<< "$1"
  readarray -t files < <(notmuch search --output=files "$thread")

  local i=0
  for file in "${files[@]}"; do
    [[ $i -ne 0 ]] && sepline
    echo "$file"; sepline
    mu view "$file"
    ((i++))
  done
}

list() {
  # @menu-mail-list inbox|sent|draft|archive
  notmuch search --sort=newest-first --output=summary tag:inbox
}

BINDS[tag]=alt-q
HOOKS[tag]=tag
CALLS[tag]='execute-silent(%s {1} {q})+reload-sync(list)'
tag() {
  local term="$1"
  notmuch tag -unread "$term"
}
