#!/usr/bin/env bash

KEY=space
MOD='S-M'
ICON=
COLOR=aqua

POSITION=RIGHT
NOWRAP=1

view() {
	local menu
	read -r menu _ <<<"$1"
	gui "$menu" list
}

list() {
	gui | column -t -s: | sort -k4
}

BINDS[open]=enter
HOOKS[open]=open
CALLS[open]='become(menu shell {2})'
DESCS[open]='Open menu entry'
open() {
  :
}
