#!/usr/bin/env bash

KEY=i
MOD='S-M'
ICON=󰐰

HORIZONTAL=1

function init() {
  set_opt mode sinks
}

function label() {
  local mode="$(get_opt mode)"

  echo " mode: $mode "
}

BINDS[rotate_mode]=alt-t
HOOKS[rotate_mode]=clear
DESCS[rotate_mode]='Rotate mode'
function rotate_mode() {
  local mode="$(get_opt mode)"

  case "$mode" in
    sinks) set_opt mode sources ;;
    sources) set_opt mode sink-inputs ;;
    sink-inputs) set_opt mode source-outputs ;;
    source-outputs) set_opt mode sinks ;;
  esac
}

function view() {
  :
}

# input
# output
# source
# sink

# set-default
# set-sink-source

# vol %5+
# vol %5-
# vol toggle
# vol mute/unmute

# edit conn
# show conn
# add wifi
# mod sublist
#   pass
#   name
#   forget?

# create aec-sink-source
# create drc-sink-source
# create surround-sink
# create combine-sink-all
# create monitored-sink?

function list() {
  # format: INDEX, SINK/SOURCE/INPUT/OUTPUT/PORT, NAME, MUTE, VOL, DEFAULT

  local mode="${1:-$(get_opt mode)}"

  set_opt mode "$mode"
  entries "$mode"
}

function entries() {
  local kind="$1"
  pactl -f json list "$kind" |
    jq -r '.[] | (.index|tostring) + " " + .description + .volume."front-left".value_percent'
}
