#!/usr/bin/env bash

KEY=r
MOD='S-M'
ICON=

export APP_DIR="$HOME/.lib/app"

function view() {
  command preview "$APP_DIR/$1"
}

function list() {
  local apps
  readarray -t apps < <(ls -1 $HOME/.lib/app)
  printf "%s\n" "${apps[@]}"
}

function key() {
  source "$HOME/.lib/app/$1"
  echo "$1:$KEY"
}

function keys() {
  for app in $(basename -a "${APP_DIR}"/*); do
    gui run key "$app"
  done
}

BINDS[edit]=alt-e
HOOKS[edit]=accept
DESCS[edit]='Edit in $EDITOR'
function edit() {
  open "$APP_DIR/$1"
}

function run() {
  local file="$1" mode="$2"

  shift 2

  source "$HOME/.lib/app/$file"

  if silent declare -F runner; then
    runner "${@:3}"
  fi
}

BINDS[fg]=enter
HOOKS[fg]=accept
DESCS[fg]='Run in the foreground'
function fg() {
  source "$HOME/.lib/app/$1"
  gui awm runonce fg "${ATTRIBUTES[@]}" -- gui run run "$1" "${@:2}"
}

BINDS[bg]=tab
DESCS[bg]='Run in the background'
function bg() {
  source "$HOME/.lib/app/$1"
  gui awm runonce bg "${ATTRIBUTES[@]}" -- gui run run "$1" "${@:2}"
}

BINDS[close]=alt-d
DESCS[close]='Terminate window'
function close() {
  source "$HOME/.lib/app/$1"
  gui awm winkill "${ATTRIBUTES[@]}"
}
