#!/usr/bin/env bash

KEY=r
MOD='S-M'
ICON=
COLOR=aqua

export APP_DIR="$HOME/.lib/app"

view() {
  local folder app
  read -r folder app _ <<< "$1"
	command preview "$APP_DIR/$folder/$app"
}

list() {
	local apps

  readarray -t apps < <(cd "$APP_DIR" && find * -type f -or -type l)

  local folder

  for app in "${apps[@]}"; do
    unset folder
    IFS=/ read -r folder app _ <<< "$app"
    printf "%s%s%s\n" "$folder" "$iSEP" "$app"
  done | column -t -s "$iSEP"

	# printf "%s\n" "${apps[@]}"
}

key() {
  local app="$1"

	source "$APP_DIR/$app"

	echo "$app:$KEY"
}

keys() {
  local apps

  readarray -t apps < <(cd "$APP_DIR" && find * -type f)

  for app in "${apps[@]}"; do
		gui run key "$app"
	done
}

BINDS[edit]=alt-e
HOOKS[edit]=accept
DESCS[edit]='Edit in $EDITOR'
edit() {
  local folder app

  read -r folder app _ <<< "$1"

	open "$APP_DIR/$folder/$app"
}

run() {
	local file="$1"

	shift 2

	source "$APP_DIR/$file"

	if silent declare -F runner; then
		runner "${@:3}"
	fi
}

spawn() {
  local folder app mode="$1"

  IFS=$'/\t ' read -r folder app _ <<< "$2"

  local ATTRIBUTES

  if [[ "$folder" == window ]]; then
    ATTRIBUTES=(profile="$app")
  fi

	source "$HOME/.lib/app/$folder/$app"

	gui awm "$mode" "${ATTRIBUTES[@]}" -- gui run run "$folder/$app" "${@:3}"
}

BINDS[fg]=enter
HOOKS[fg]=accept
DESCS[fg]='Run in the foreground'
fg() {
  spawn fg "$@"
}

BINDS[bg]=tab
DESCS[bg]='Run in the background'
bg() {
  spawn bg "$@"
}

BINDS[close]=alt-d
DESCS[close]='Terminate window'
close() {
  local folder app

  read -r folder app _ <<< "$1"

	source "$HOME/.lib/app/$folder/$app"

	gui awm winkill "${ATTRIBUTES[@]}"
}
