#!/usr/bin/env bash

KEY=s
MOD='S-M'
ICON=

NOWRAP=1

export UEBERZUG_PREVIEW=1

function init() {
  #set_opt pwd "$HOME/.marks"
  [[ -n "$(get_opt pwd)" ]] || set_opt pwd "$HOME/.marks"
  set_opt hide 0
  set_opt mode 0
  set_opt mode-mod 3
}

function folder_save() {
  set_opt pwd "$(pwd)"
}

function folder_restore() {
  FOLDER="$(get_opt pwd)"
}

function path() {
  local path="$(filter all "$1")"

  folder_restore

  if [[ "${path:0:1}" == / ]]; then
    realpath -s "$path"
  else
    realpath -s "$FOLDER/$path"
  fi
}

function folder_cd() {
  cd "$(path "$1")" && folder_save
}

function label() {
  local path="$(path "$FOLDER")"
  local mode="$(get_opt mode)"
  local hide="$(get_opt hide)"
  printf "%s - hide = %s - mode = %s" "$path" "$hide" "$mode"
}

function mimetype() {
  # assuming valid absolute path
  local path="$(path "$1")"

  printf "%s (%s - %s)\n" "$path" "$(file -bL --mime-type "$path")" \
    "$(du -hs "$path" | awk '{print $1}')"
}

function view() {
  local path="$(path "$1")"

  mimetype "$path"
  sepline
  command preview "$path"
}

function state_update() {
  folder_restore
  restore_opt hide

  read -r HIDE < <(get_opt hide)
  read -r MODE < <(get_opt mode)

  case "$HIDE" in
    1)
      LSD_OPTS=('-A')
      FD_OPTS=('-H')
        ;;
    0)
      LSD_OPTS=()
      FD_OPTS=()
        ;;
  esac

  case "$MODE" in
    0) FD_OPTS+=(-td) ;; # find dirs
    1) FD_OPTS+=(-tf) ;; # find files
    2) FD_OPTS+=(-tl) ;; # find links
    *) ;;
  esac

  FD_OPTS+=(--base-directory "$FOLDER")

  LIST_CMD=(lsd -1 --no-symlink --group-dirs=first "${LSD_OPTS[@]}")
  SEARCH_CMD=(fd "${FD_OPTS[@]}")
}

BINDS[list]=alt-w
DESCS[list]='Reload current directory listing'
function list() {
  local dir="$1"

  state_update

  if [[ -n "$dir" ]]; then
    folder_cd "$dir" && folder_restore
  fi

  "${LIST_CMD[@]}" "$FOLDER/"
}

BINDS[search]=alt-s
HOOKS[search]=search
CALLS[search]='reload-sync(%s {} {q})+clear-query'
DESCS[search]='Search arbitrary pattern with fd'
function search() {
  state_update
  cd "$FOLDER" && "${SEARCH_CMD[@]}" "$2"
}

BINDS[goto]=ctrl-t
HOOKS[goto]=accept
DESCS[goto]='Cd to FOLDER in shell'
function goto() {
  state_update
  set_opt cdir "$FOLDER"
}

BINDS[rotate_mode]=alt-y
HOOKS[rotate_mode]=search
DESCS[rotate_mode]='Rotate mode'
function rotate_mode() {
  rotate_opt mode
  search "$1" "$2"
}

BINDS[toggle_hide]=alt-t
DESCS[toggle_hide]='Toggle hidden'
function toggle_hide() {
  toggle_opt hide
}

BINDS[rename]=alt-r
HOOKS[rename]=sclear
DESCS[rename]='Prompt rename entry'
function rename() {
  folder_restore
  local entry="$1"

  export MENU_INPUT_PREVIEW="$entry"

  read -r input < <(cd "$FOLDER" && input "$entry")
  mv -- "$FOLDER/$entry" "$FOLDER/$input"
}

BINDS[mark]=alt-m
DESCS[mark]='Mark entry'
function mark() {
  local path="$(path "$1")"

  local marksdir="$HOME/.marks"

  local target="$(realpath -m --relative-to="$marksdir" "$path")"

  local link="$(basename "$path")"

  (cd "$marksdir" && ln -svf "$target" "${link#.}")
}

BINDS[attach]=alt-f
DESCS[attach]='Select entry'
function attach() {
  local path="$(path "$1")"
  mkdir -p "$HOME/.selections"
  ln -svf "$path" "$HOME/.selections"
}

BINDS[marks]=alt-space
DESCS[marks]='Go to marks directory'
function marks() {
  save_opt hide
  set_opt hide 0
  folder_cd "$HOME/.marks"
}

BINDS[home]=alt-q
DESCS[home]='Home directory'
function home() {
  folder_cd "$HOME"
}

BINDS[add]=alt-a
DESCS[add]='Create directory'
function add() {
  local query="$2"
  folder_restore
  mkdir -p "$FOLDER/$query"
}

BINDS[del]=alt-d
DESCS[del]='Delete entry definitively'
function del() {
  rm -rf "$(path "$1")"
}

BINDS[open]=tab
HOOKS[open]=noclear
DESCS[open]='Open entry'
function open() {
  command open "$(path "$1")"
}

BINDS[_open]=alt-enter
HOOKS[_open]=accept
DESCS[_open]='Open entry and quit'
function _open() {
  open "$1"
}

BINDS[vimsession]=alt-u
HOOKS[vimsession]=accept
DESCS[vimsession]='Open vim project and quit'
function vimsession() {
  command open "$(path "$1")" nvim
}

BINDS[enter]=enter
DESCS[enter]='Change Directory'
function enter() {
  folder_cd "$1"
}

BINDS[back]=esc
DESCS[back]='Parent Directory'
function back() {
  folder_cd ..
}

function atfinish() {
  #unset_opt pwd
  unset_opt hide
  unset_opt mode
}
