#!/usr/bin/env bash

KEY=l
MOD='S-M'
ICON=
ICON=
ICON=
COLOR=yellow

export ALACRITTY_DIR="$HOME/.config/alacritty"
export PREVIEW_FILE="$HOME/.UTF-8-demo.txt"

atfinish() {
	(
		cd "$ALACRITTY_DIR"
		read -r orig < <(basename "$(realpath font-name.link.toml)")
		ln -vf "fonts/${orig}" font-name.toml
	)
}

label() {
	local font size
	read -r size < <(size get)
	read -r font < <(basename $(realpath "${ALACRITTY_DIR}/font-name.link.toml"))
	echo "${font} (${size})"
}

view() {
	local font size
	read -r size < <(size get)
	read -r font <<<"$1"
	(
		cd "$ALACRITTY_DIR"
		ln -f "fonts/${font}" font-name.toml
	)

	command preview "$ALACRITTY_DIR/fonts/${font}"
	sepline
	command preview "$PREVIEW_FILE"
}

list() {
	fd --base-directory "$ALACRITTY_DIR/fonts" -e toml
	# themes
	# wallpapers
}

BINDS[link]=enter
DESCS[link]='Link font entry'
link() {
	local font
	read -r font <<<"$1"
	(
		cd "$ALACRITTY_DIR"
		ln -vf "fonts/${font}" font-name.toml
		ln -svf "fonts/${font}" font-name.link.toml
	)
}

size() {
	local file="${ALACRITTY_DIR}/font-size.toml"
	case "$1" in
	get) sed -rn '/size/s/[^[:digit:]\.]//gp' "${file}" ;;
	set)
		cat <<EOF >"$file"
[font]
size = ${2}
EOF
		;;
	esac
}

BINDS[inc]=alt-n
HOOKS[inc]=noclear
DESCS[inc]='Increase size'
inc() {
	local size
	read -r size < <(size get)
	size set "$(echo "$size + 0.1" | bc)"
}

BINDS[dec]=alt-p
HOOKS[dec]=noclear
DESCS[dec]='Decrease size'
dec() {
	local size
	read -r size < <(size get)
	size set "$(echo "$size - 0.1" | bc)"
}
