#!/usr/bin/env bash

KEY=e
MOD='S-M'
ICON=

export MUXSOCK="$HOME/.vmux.S"
export SOCKDIR="$HOME/.sockets"
export HOSTDIR="$HOME/.ssh/hosts"

export URL=https://raw.githubusercontent.com/zenhog/dotfiles/master/bin/dotfiles

function view() {
  ssh -G "$1"
}

function list() {
  local hosts

  readarray -t hosts < <(find "$HOSTDIR" -type f -exec grep '^Host ' {} \;)

  for host in "${hosts[@]}"; do
    read -r _ host <<< "$host"

    if connected "$host"; then
      host="$(ansi --green "$host")"
    fi

    printf "%s\n" "$host"
  done | sort
}

function connected() {
  local host="$1"

  mute ssh -S "$SOCKDIR/$host.S" -O check "$host"
}

function connect() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  if [[ -n "$SSH_CONNECTION" ]] || connected "$host"; then
    return
  fi

  rm -f "$SOCKDIR/$sock"

  timeout 2 ssh -fMNS "$sock" "$host"
}

function disconnect() {
  local host="$1"
  local sock="$HOSTDIR/$host.S"

  if connected "$host"; then
    ssh -S "$sock" -O cancel "$host"
    ssh -S "$sock" -O exit   "$host"
  fi
}

BINDS[toggle]=tab
DESCS[toggle]='Toggle ssh master connection'
function toggle() {
  local host="$1"

  if connected "$host"; then
    disconnect "$1"
  else
    connect "$1"
  fi
}

function revport() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  if connected "$host"; then
    ssh -S "$sock" -O forward -R "localhost:0:$MUXSOCK" "$host"
  fi
}

function cancel() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  if connected "$host"; then
    ssh -S "$sock" -O cancel "$host"
  fi
}

BINDS[mux]=enter
HOOKS[mux]=acceptsync
DESCS[mux]='Attach a tmux session'
function mux() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"
  local name="${host%%.*}"

  attach fg "$name" "$host"
}

function attach() {
  local mode="$1"
  local name="$2"
  local host="$3"

  if ! connected "$host"; then
    connect "$host"
  fi
  gui tmux mod "$mode" attach remote "$name" "$host"
}

BINDS[shell]='alt-enter'
HOOKS[shell]=acceptsync
DESCS[shell]='Open a new shell window in tmux'
function shell() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"
  local name="${host%%.*}"

  if connect "$host"; then
    gui tmux window local "$(hostname)" "$name" \
      ssh -S "$sock" -t "$host" zsh -il
  fi
}

function mount() {
  local host="$(get host "$1")"

  mkdir -p "$HOME/.sshfs/$host"

  sshfs "$host":'$HOME' "$HOME/.sshfs/$host"
}

#function goto() {
#  mount && cd
#}

#function authorize() {
#  ssh-copy-id ???
#}

function ttyexec() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  shift

  #connect "$host" && ssh -S "$sock" -t "$host" bash -lc "'$*'"
  if connected "$host"; then
    exec ssh -S "$sock" -t "$host" bash -lc "$(printf " %q" "$*")"
  fi
}

function rexec() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  shift

  #connect "$host" && ssh -S "$sock" "$host" bash -lc "'$*'"
  #connect "$host" && ssh -S "$sock" "$host" bash -ls < <(printf " %q" "$@")

  if connected "$host"; then
    ssh -S "$sock" "$host" bash -ls <<< "${@@Q}"
  fi
}

function sync() {
  local host="$1"
  local sock="$SOCKDIR/$host.S"

  local cmd

  read -r cmd < <(printf '<(curl -sL %s)' "$URL")

  cmd=(bash "$cmd" install master)

  local temp="$(mktemp --dry-run)"

  if connected "$host"; then
    ssh -S "$sock" "$host" bash -ls << EOF
    curl -sSL "$URL" -o "$temp"
    if bash "$temp" install master; then
      bash "$temp" pull master
    fi
    rm -f "$temp"
EOF
  fi
}
