#!/usr/bin/env bash

KEY=h
MOD='S-M'
ICON=󱑎
COLOR=bisque

# HORIZONTAL=1
NOWRAP=1
RATIO=60%
FOLLOW=1

label() {
  local tz
  IFS=$'/' read -r _ _ _ _ tz < <(readlink /etc/localtime)
  echo " [ $tz ] "
}

view() {
  # weather for the timezone?
  # holiday events for the timezone?
  # cal --color=always -m -y
  local year="$(date +%Y)"
  khal --color calendar "$year-01-01" "$year-12-31"
}

# OPTS+=(--preview-window hidden)
list() {
  local tzdir=/usr/share/zoneinfo
  local tzs

  readarray -t tzs < <(cd "$tzdir" && find * -mindepth 1 -type f -or -type l)

  for tz in "${tzs[@]}"; do
    printfmt "$tz" "$(TZ=$tz date "+%H:%M %a %b %d")"
  done | column -t -s "$iSEP"
}

BINDS[open]=enter
DESCS[open]='Change timezone and sync with NTP'
open() {
  local tz

  read -r tz _ <<< "$1"

  sudo ln -svf "/usr/share/zoneinfo/$tz" /etc/localtime
  sync
  widget timedate timeout
}

sync() {
  sudo ntpdate pool.ntp.org && sudo hwclock --systohc --utc
}
