#!/usr/bin/env bash

KEY=h
MOD='S-M'
ICON=󱑎
COLOR=bisque

# HORIZONTAL=1
NOWRAP=1
RATIO=60%
FOLLOW=1

label() {
  local tz
  IFS=$'/' read -r _ _ _ _ tz < <(readlink /etc/localtime)
  echo " [ $tz ] "
}

weather() {
  local city="$1"
  local apikey="$(pass show iz/www/weather/tomorrow.io/0/apikey)"

  local endpoint='https://api.tomorrow.io/v4/weather'

  local query response

  read -r query < <(printf '%s/realtime?location=%s&apikey=%s' \
    "$endpoint" "$city" "$apikey"
  )

  read -r response < <(curl -sSL "$query")

  local icon code desc realtemp feeltemp hum lat lon name

  read -r code < <(jq -r '.data.values.weatherCode' <<< "$response")
  read -r realtemp < <(jq -r '.data.values.temperature' <<< "$response")
  read -r feeltemp < <(jq -r '.data.values.temperatureApparent' <<< "$response")
  read -r hum < <(jq -r '.data.values.humidity' <<< "$response")
  read -r lat < <(jq -r '.location.lat' <<< "$response")
  read -r lon < <(jq -r '.location.lon' <<< "$response")
  read -r name < <(jq -r '.location.name' <<< "$response")

  read -r desc < <(
    jq -r ".weatherCode.\"$code\"" < "$HOME/.lib/data/weather_codes.json")

  for val in name lat lon realtemp feeltemp hum desc; do
    eval echo "$val$iSEP\$$val"
  done | column -t -s "$iSEP" -o "$oSEP"
}

view() {
  # weather for the timezone?
  # holiday events for the timezone?
  local continent city

  read -r continent _ <<< "$1"

  IFS=/ read -r continent city <<< "$continent"

  weather "$city"
}

# OPTS+=(--preview-window hidden)
list() {
  local tzdir=/usr/share/zoneinfo
  local tzs

  readarray -t tzs < <(cd "$tzdir" && find * -mindepth 1 -type f -or -type l)

  for tz in "${tzs[@]}"; do
    printfmt "$tz" "$(TZ=$tz date "+%H:%M %a %b %d")"
  done | column -t -s "$iSEP"
}

BINDS[open]=enter
DESCS[open]='Change timezone and sync with NTP'
open() {
  local tz

  read -r tz _ <<< "$1"

  sudo ln -svf "/usr/share/zoneinfo/$tz" /etc/localtime
  sync
  widget timedate timeout
}

sync() {
  sudo ntpdate pool.ntp.org && sudo hwclock --systohc --utc
}
