#!/bin/bash

exec 2>&1

SDIR="/home/stuck/.remotes"
SOCK="$SDIR/$(hostname).S"

echo "********* Log from $(date) ***********"

ssh -T hashbang "mkdir -p $SDIR ; rm $SOCK"
exec ssh -t -R "$SOCK":localhost:22 hashbang zsh
