#!/usr/bin/env bash

notify() {
  notify-send -t 5000 -a "${0##*-}" "$1" "${*:2}"
}

case "${0##*-}" in
  complete)
    notify Completed "$(basename "$3")"
    ;;
  error)
    notify Failed "$(basename "$3")"
    ;;
  pause)
    ;;
  start)
    notify Added "$(basename "$3")"
    ;;
  stop)
    notify Stopped "$(basename "$3")"
    ;;
esac

widget download timeout
