#!/usr/bin/env bash

F="$HOME/.config/neomutt/config/mailboxes"

readarray -t mailboxes < <(awk '/^virtual-mailboxes/{print $2}' "$F" | tr -d '"')

mailbox="$(printf "%s\n" "${mailboxes[@]}" | fzf)"

if [[ "$mailbox" == */* ]]; then
  folder="$(sed -rn 's/\[(.*)\].*/\1/p' <<< "$mailbox")"
fi

echo "push 'c$mailbox<enter>'"

#[[ -n "$folder" ]] &&
#echo "push ':source ~/.config/neomutt/config/accounts/${folder~}.neomuttrc'"
