#!/bin/sh

exec 2>&1

export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh


# exec snooze -v -H\* -M\* cgexec -g net_cls:wan mbsync -a mailbox
snooze -v -H\* -M\* -t "$PWD/timefile" mailsync

touch "$PWD/timefile"
