#!/bin/sh

exec 2>&1

modprobe -q loop || exit 1

mountpoint -q /sys/fs/cgroup/systemd || {
  mkdir -p /sys/fs/cgroup/systemd
  mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
}

exec /usr/libexec/incus/incusd --group _incus-admin
